### ISSUE TITLE
API create subjects 

### ISSUE THREAD

**Issue by alexanderkgonzalez** [chop-dbhi/biorepo-portal#110]
Perhaps we  can think about write  ability for API subjects

**Comment by tjrivera** [comment]
Since the BRP is designed as javascript front-end + rest API pretty much everything that you can do (until your in a specific "datasource" i.e. creating a redcap record) in the application has an API that drives it. 

The API for creating subjects is driven by [this view](https://github.com/chop-dbhi/biorepo-portal/blob/master/api/views/protocol.py#L200-L313) and is exposed via [this endpoint](https://github.com/chop-dbhi/biorepo-portal/blob/master/api/urls.py#L20-L21)

**Comment by tjrivera** [comment]
here's [an example test](https://github.com/chop-dbhi/biorepo-portal/blob/master/api/tests/test_views.py#L217-L269) that demonstrates usage.

**Comment by alexanderkgonzalez** [comment]
Just seeing this! This is great.
We can close the issue @tjrivera
